services:
  # --------------------------------------------------------------------------------
  # BACKEND (Docker)
  # --------------------------------------------------------------------------------
  - type: web
    name: videoinsight-backend
    env: docker
    dockerContext: ./server
    dockerfilePath: ./server/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8000
      - key: SERVER_URL
        value: https://videoinsight-9ma9.onrender.com
      - key: CLIENT_URL
        value: https://video-insight-five.vercel.app
      - key: MONGO_URI
        value: mongodb://shivamnith098_db_user:qYePk1R3M3aIOL11@ac-laatph9-shard-00-00.oazj7fk.mongodb.net:27017,ac-laatph9-shard-00-01.oazj7fk.mongodb.net:27017,ac-laatph9-shard-00-02.oazj7fk.mongodb.net:27017/videoinsight?ssl=true&replicaSet=atlas-lex327-shard-0&authSource=admin&appName=Cluster0
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PYTHON_BIN
        value: python3
      - key: TRANSCRIPT_LANGS
        value: en,en-US,en-GB,en-IN,hi


